<a href="https://colab.research.google.com/github/Gabrielhfalcao/estudos_Numpy/blob/main/testeNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [11]:
a = np.array([[0, 0, 4], [0, 5, 9]])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(len(a))

[[0 0 4]
 [0 5 9]]
<class 'numpy.ndarray'>
2
(2, 3)
2


In [19]:
b = np.arange(0, 100, 2)
print(b)

c = np.arange(10)
print(c)

d = np.linspace(1, 10, 20, endpoint=False)
print(d)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
[0 1 2 3 4 5 6 7 8 9]
[1.   1.45 1.9  2.35 2.8  3.25 3.7  4.15 4.6  5.05 5.5  5.95 6.4  6.85
 7.3  7.75 8.2  8.65 9.1  9.55]


In [29]:
e = np.ones((5, 5))
print(e)

f = np.zeros(100)
print(f)

g = np.random.rand(10, 10)
print(g)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[[0.70263576 0.38737802 0.88892653 0.7370839  0.18249215 0.31061123
  0.16880229 0.72965209 0.7167579  0.13005106]
 [0.73968365 0.39529902 0.44273954 0.14320315 0.90096627 0.48119671
  0.14972339 0.03627112 0.01736767 0.09366721]
 [0.1577566  0.11151023 0.60138258 0.64642941 0.77100399 0.13947263
  0.81248422 0.90697773 0.32052905 0.08320337]
 [0.48438775 0.7233278  0.88967872 0.09224194 0.83900961 0.05049981
  0.51137523 0.97804422 0.00858497 0.11161124]
 [0.2615046  0.51087404 0.54251946 0.50756924 0.51920718 0.70491243
  0.26328426 0.73472676 0.28100616 0.92751304]
 [0.27636796 0.8616159  0.49

In [34]:
h = np.eye(3, 3)
print(h)

i = np.diag([1, 2, 3, 4])
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [40]:
j = np.random.rand(5, 5)
print(j)
j[0, 1]

j[0][1] = 10
print(j)

[[0.26788465 0.3367821  0.89139407 0.06100212 0.34319114]
 [0.47948435 0.99352071 0.37070462 0.40169816 0.43611549]
 [0.34241727 0.05715597 0.15148954 0.24460197 0.40723473]
 [0.81846341 0.60930461 0.5692399  0.30399464 0.23728385]
 [0.87765024 0.56170803 0.57110196 0.54656618 0.1785059 ]]
[[ 0.26788465 10.          0.89139407  0.06100212  0.34319114]
 [ 0.47948435  0.99352071  0.37070462  0.40169816  0.43611549]
 [ 0.34241727  0.05715597  0.15148954  0.24460197  0.40723473]
 [ 0.81846341  0.60930461  0.5692399   0.30399464  0.23728385]
 [ 0.87765024  0.56170803  0.57110196  0.54656618  0.1785059 ]]


In [43]:
a = np.arange(0, 10)
print(a)
print(a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [47]:
b = np.random.rand(5, 5)
print(b)
print(b[0: , 1])

[[7.98317188e-01 2.62681104e-01 1.52274890e-01 3.10717226e-02
  6.76796478e-01]
 [1.20517133e-01 1.45657844e-02 1.29091926e-01 8.06311388e-01
  5.35661604e-04]
 [8.63945883e-01 9.24704859e-01 2.26264777e-01 5.58960003e-01
  8.34532566e-01]
 [7.88665435e-01 7.12300316e-01 3.73548392e-01 8.92468692e-02
  9.78670454e-01]
 [2.87640116e-01 3.92101285e-01 9.73545327e-01 7.48767853e-01
  6.29529459e-01]]
[0.2626811  0.01456578 0.92470486 0.71230032 0.39210129]


In [67]:
np.random.seed(1)
a1 = np.random.randint(1, 10, 5)
print(a1)


[6 9 6 1 1]


In [69]:
a1 + 2

array([ 8, 11,  8,  3,  3])

In [71]:
a1**2

array([36, 81, 36,  1,  1])

In [77]:
a2 = np.random.randint(1, 10, 5)
print(a2)

[8 7 2 1 2]


In [79]:
a1 + a2

array([14, 16,  8,  2,  3])

In [83]:
m1 = np.ones((3, 2))
m2 = np.ones((2, 3))

print(m1)
print("\n")
print(m2)
print("\n")

m1.dot(m2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


[[1. 1. 1.]
 [1. 1. 1.]]




array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [88]:
a1 = np.array([1, 2, 3])
a2 = np.array([1, 3, 5])

print(a1 == a2)
print('\n')
np.array_equal(a1, a2)

[ True False False]




False